sudo: required

services:
  - docker
  
before_install:
  - docker build -t govkumardocker/sp-security-db:1.0.0-SNAPSHOT .
  
script:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  - docker push govkumardocker/sp-security-db:1.0.0-SNAPSHOT